server/config/urls.py
import django
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('seriados/', include('seriados.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

server/seriados/urls.py
from django.urls import include, path, re_path, register_converter
from django.views.generic import TemplateView

from . import views

app_name = 'seriados'

urlpatterns = [
    #path('series/',views.series_list, name='series_list'),
    #path('series/<int:pk>/', views.series_details, name='series_details'),

    
    path('episodios/',views.episodios_list,name='episodios_list'),
    path('episodios/<int:pk>/', views.episodios_details, name='episodios_details'),
    path('episodios/inserir/', views.EpisodioCreateView.as_view(),name='episodios_insert'),
    path('episodios/<int:pk>/editar', views.EpisodiosUpdateView.as_view(),name='episodios_update'),
    path('episodios/<int:pk>/excluir/', views.EpisodiosDeleteView.as_view(),name='episodios_excluir'),
    path('episodios/busca/', views.EpisodiosBuscaLisView.as_view(),name='episodios_busca_list'),
    
    path('episodios/nota/<str:nota>/', views.episodio_nota_list,name='episodio_nota_list'),
    
    path('revisores/',views.revisores_list,name='revisores_list'),
    path('revisores/<int:pk>/', views.revisores_details, name='revisores_details'),
    path('revisores/inserir/', views.RevisoresCreateView.as_view(), name='revisores_insert'),
    path('revisores/<int:pk>/editar', views.RevisoresUpdateView.as_view(),name='revisores_update'),
    path('revisores/<int:pk>/excluir/', views.RevisoresDeleteView.as_view(),name='revisores_excluir'),
    
    path('review_episodios/',views.review_episodios_list,name='review_episodios_list'),
    path('review_episodios/<int:pk>/', views.review_episodios_details, name='review_episodios_details'),
    path('review_episodios/inserir/', views.ReviewEpisodiosCreateView.as_view(), name='review_episodios_insert'),
    path('review_episodios/<int:pk>/editar', views.ReviewEpisodiosUpdateView.as_view(),name='review_episodios_update'),
    path('review_episodios/<int:pk>/excluir/', views.ReviewEpisodiosDeleteView.as_view(),name='review_episodios_excluir'),
    
    path('sobre/', TemplateView.as_view(template_name="about.html"), name='about'),
    path('contato/', views.Contact.as_view(), name='contact'),
   
    path('home', views.HomeView.as_view(), name='home'),
    path('', views.HomeView.as_view(), name='home'),
    
    path('temporadas/', views.TemporadaListView.as_view(), name='temporadas_list'),
    path('temporadas/<int:pk>/', views.TemporadaDetails.as_view(), name='temporadas_details'),
    path('temporadas/inserir/', views.TemporadaCreateView.as_view(), name='temporadas_insert'),
    path('temporadas/<int:pk>/editar', views.TemporadaUpdateView.as_view(),name='temporadas_update'),
    path('temporadas/<int:pk>/excluir/', views.TemporadaDeleteView.as_view(),name='temporadas_excluir'),
    
    path('series/', views.SerieListView.as_view(), name='series_list'),
    path('series/<int:pk>/', views.SerieDetailsView.as_view(), name='series_details'),
    path('series/inserir/',views.series_insert, name='series_insert'),
    path('series/<int:pk>/editar', views.SeriesUpdateView.as_view(),name='series_update'),
    path('series/<int:pk>/excluir/', views.SeriesDeleteView.as_view(),name='series_excluir'),
  
    path('blog',views.blog_list,name='blog_list'),
    path('blog/<int:pk>/', views.post_details,name='blog_post'),
    path('blog/categoria/<int:pk>/', views.categorias_details,name='blog_categorias'),





   ]   

server/seriados/forms.py
from django import forms

from .models import Episodio, ReviewEpisodio, Revisor, Serie, Temporada


class SerieForm(forms.Form):
    nome = forms.CharField(label="Nome da Série", max_length=70)

class TemporadaForm(forms.ModelForm):
    
    class Meta:
        model = Temporada
        fields = ['numero','serie']

class RevisoresForm(forms.ModelForm):
    
    class Meta:
        model = Revisor
        fields = ['user','reviews_episodios']

class ReviewEpisodiosForm(forms.ModelForm):
    
    class Meta:
        model = ReviewEpisodio
        fields = ['episodio','revisor','nota']

server/seriados/views.py
from re import template

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.db.models import Q
from django.forms.models import model_to_dict
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import ReviewEpisodiosForm, RevisoresForm, SerieForm, TemporadaForm
from .models import (Blog, Categoria, Episodio, ReviewEpisodio, Revisor, Serie,
                     Temporada)


def prepare_data_list(objects, fields_name):
    labels = list()
    for field_name in fields_name:
        field = objects.model._meta.get_field(field_name)
        labels.append(field.verbose_name)
    
    rows = list()
    for _object in objects:
        row = dict()
        rows.append(row)
        row['pk'] = _object.pk
        row['data'] = list()
        for field_name in fields_name:
            row['data'].append(getattr(_object, field_name))
    
    return labels, rows


def prepare_data_detail(_object, fields_name):
    data = model_to_dict(_object)
    rows = list()
    for field_name in fields_name:
        field = _object._meta.get_field(field_name)
        rows.append({'label': field.verbose_name, 'value': data[field_name]})
    return rows

@login_required
@permission_required('seriados.view_episodio', raise_exception=True)
def episodios_details(resquest, pk):
    _object = get_object_or_404(Episodio, pk=pk)
    context = {
        'title': "Episódios",
        'data': prepare_data_detail(_object, ['titulo', 'data']),   
    }
    return render(resquest, 'details.html', context)
  
@login_required
@permission_required('seriados.view_episodio', raise_exception=True)
def episodios_list(request):
    search = request.GET.get('search',"")
    objects = Episodio.objects.filter(titulo__contains=search)
    labels, rows = prepare_data_list(objects,['titulo','data'] )
    context = {
        'title': "Episódios",
        'labels': labels,
        'rows': rows,
        'detail_url': 'seriados:episodios_details',
        'list_url': 'seriados:episodios_list',
    }
    return render(request, 'list.html', context)

class EpisodioCreateView(LoginRequiredMixin,PermissionRequiredMixin, CreateView):
    permission_required='seriados.add_episodio'
    template_name = 'form_generic.html'
    model = Episodio
    fields = ['temporada','data','titulo']
    
class EpisodiosUpdateView(LoginRequiredMixin,PermissionRequiredMixin, UpdateView):
    permission_required = ('seriados.view_episodio','seriados.change_episodio')
    template_name = 'form_generic.html'
    model = Episodio
    fields = ['temporada','data','titulo'] 
       
class EpisodiosDeleteView(LoginRequiredMixin,PermissionRequiredMixin, DeleteView):
    permission_required='seriados.delete_episodio'
    template_name = 'episodios_cohfirm_delete.html'
    model = Episodio
    
    def get_success_url(self):
        return reverse('seriados:episodios_list')


class EpisodiosBuscaLisView(LoginRequiredMixin,PermissionRequiredMixin, ListView):
    permission_required='seriados.view_episodio'
    template_name = 'episodios_busca_list.html'
    model = Episodio
    
    def get_queryset(self):
        search = self.request.GET.get('search', "")
        q = Q(titulo__contains=search) | Q(temporada__serie__nome__contains=search)
        for term in search.split():
            q = q | Q(titulo__contains=term)
            q = q | Q(temporada__serie__nome__contains=term)
            try:
                i_term = int(term)
            except ValueError:
                pass
            else:
                q = q | Q(temporada__numero=i_term)
        qs = super().get_queryset().filter(q)
        return qs

@login_required
@permission_required('seriados.view_revisor', raise_exception=True)
def revisores_details(resquest, pk):
    _object = get_object_or_404(Revisor, pk=pk)
    context = {
        'title': "Revisores",
        'data': prepare_data_detail(_object, ['user', 'reviews_episodios']),
    }
    return render(resquest, 'details.html', context)
  
@login_required
@permission_required('seriados.view_revisor', raise_exception=True)
def revisores_list(request):
    search = request.GET.get('search',"")
    if search == "" :
        objects = Revisor.objects.all()
    else:
        objects = Revisor.objects.filter(user_id=search)
    
    labels, rows = prepare_data_list(objects,['user'] )
    context = {
            'title': "Revisores",
            'labels': labels,
            'rows': rows,
            'detail_url': 'seriados:revisores_details',
            'list_url': 'seriados:revisores_list',

    }
    return render(request, 'list.html', context)

class RevisoresCreateView(LoginRequiredMixin,PermissionRequiredMixin, CreateView):
    permission_required = 'seriados.add_revisor'
    template_name = 'form_generic.html'
    form_class = RevisoresForm
    
class RevisoresUpdateView(LoginRequiredMixin,PermissionRequiredMixin, UpdateView):
    permission_required = ('seriados.view_revisor','seriados.change_revisores')
    template_name = 'form_generic.html'
    model = Revisor
    fields = ['user','reviews_episodios']
    
class RevisoresDeleteView(LoginRequiredMixin,PermissionRequiredMixin, DeleteView):
    permission_required='seriados.delete_revisor'
    template_name = 'revisores_cohfirm_delete.html'
    model = Revisor
    
    def get_success_url(self):
        return reverse('seriados:revisores_list')

@login_required
@permission_required('seriados.view_reviewepisodio', raise_exception=True)
def review_episodios_details(resquest, pk):
    _object = get_object_or_404(ReviewEpisodio, pk=pk)
    context = {
        'title': "Review Episodios",
        'data': prepare_data_detail(_object, ['episodio', 'revisor','nota']),
    }
    return render(resquest, 'details.html', context)
  
@login_required
@permission_required('seriados.view_reviewepisodio', raise_exception=True)
def review_episodios_list(request):
    search = request.GET.get('search',"")
    if search == "" :
        objects = ReviewEpisodio.objects.all()
    else:
        objects = ReviewEpisodio.objects.filter(episodio_id=search)
    labels, rows = prepare_data_list(objects,['episodio','revisor','nota'] )
    context = {
        'title': "Review Episodios",
        'labels': labels,
        'rows': rows,
        'detail_url': 'seriados:review_episodios_details',
        'list_url': 'seriados:review_episodios_list',

    }
    return render(request, 'list.html', context)

    

class ReviewEpisodiosCreateView(LoginRequiredMixin,PermissionRequiredMixin, CreateView):
    permission_required='seriados.add_reviewepisodio'
    template_name = 'form_generic.html'
    form_class = ReviewEpisodiosForm
    
class ReviewEpisodiosUpdateView(LoginRequiredMixin,PermissionRequiredMixin, UpdateView):
    permission_required = ('seriados.view_reviewepisodio','seriados.change_reviewepisodio')
    template_name = 'form_generic.html'
    model = ReviewEpisodio
    fields = ['episodio','revisor','nota']
    
class ReviewEpisodiosDeleteView(LoginRequiredMixin,PermissionRequiredMixin, DeleteView):
    permission_required='seriados.delete_reviewepisodio'
    template_name = 'revisores_episodios_cohfirm_delete.html'
    model = ReviewEpisodio
    
    def get_success_url(self):
        return reverse('seriados:review_episodios_list')

@login_required
@permission_required('seriados.view_episodio', raise_exception=True)
def episodio_nota_list(request, nota):
    objects = Episodio.objects.filter(reviewepisodio__nota=nota)
    context = {'objects': objects, 'nota':nota,}
    return render(request, 'episodio_nota_list.html', context)

class Contact(TemplateView):
    template_name= 'contact.html'

class HomeView(View):
    def get(self, request):
        return render(request, 'home.html', {})

class TemporadaListView(LoginRequiredMixin,PermissionRequiredMixin, ListView):
    permission_required='seriados.view_temporada'
    template_name = 'temporada_list.html'
    model = Temporada
    
    def get_queryset(self):
        search = self.request.GET.get('search', "")
        q = Q(serie__nome__contains=search)
        for term in search.split():
            q = q | Q(serie__nome__contains=term)
            try:
                i_term = int(term)
            except ValueError:
                pass
            else:
                q = q | Q(numero=i_term)
        qs = super().get_queryset().filter(q)
        return qs
    
     
    
class TemporadaDetails(LoginRequiredMixin,PermissionRequiredMixin, DetailView):
    permission_required = 'seriados.view_temporada'
    template_name = 'temporada_details.html'
    model = Temporada
    
class TemporadaCreateView(LoginRequiredMixin,PermissionRequiredMixin, CreateView):
    permission_required = 'seriados.add_temporada'
    template_name = 'form_generic.html'
    form_class = TemporadaForm
    
class TemporadaUpdateView(LoginRequiredMixin,PermissionRequiredMixin, UpdateView):
    permission_required = ('seriados.view_temporada','seriados.change_temporada')
    template_name = 'form_generic.html'
    model = Temporada
    fields = ['serie','numero']
    
class TemporadaDeleteView(LoginRequiredMixin,PermissionRequiredMixin, DeleteView):
    permission_required='seriados.delete_temporada'
    template_name = 'temporada_cohfirm_delete.html'
    model = Temporada
    
    def get_success_url(self):

server/seriados/templates/about.html
{% extends 'base.html' %}
{% block content %}
    Sistema para cadastro e reviews de Seriados!
    <br>
    <b>Curso de Especialização em Python para Negócios</b>
    <p>
        <a href="{% url 'seriados:contact' %}">Contato</a>
    </p>
{% endblock content %}

server/seriados/templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Python para Negócios</title>
        <meta charset="utf-8">

        <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous">
        </script>
        <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}" ></script>
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    {% block navbar %}
                        {% include 'navbar.html' %}
                    {% endblock %}
                </div>
            </nav>

            {% block content %}
                <p>Não há nenhum conteúdo aqui!</p>
            {% endblock %}
        </div>
    </body>
</html>

server/seriados/templates/blog.html
{% extends "base.html" %}
{% block title %}Bem vindo ao Blog {% endblock %}

{% block content %}
    <h2>Categorias</h2>
    {% if categorias %}
        <ul>
        {% for categoria in categorias %}
            <li><a href={% url detail_url_categorias  pk=categoria.pk  %}>{{ categoria.titulo }}</a></li>

        {% endfor %}
        </ul>
    {% else %}
        <p>Não há nenhuma categoria adicionada.</p>
    {% endif %}

    <h2>Posts</h2>
    {% if posts %}
        <ul>
        {% for post in posts %}
            <li><a href={% url detail_url_post pk=post.pk %}>{{ post.titulo }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Não há nenhum post adicionado.</p>
    {% endif %}

{% endblock content %}

server/seriados/templates/contact.html
{% extends 'base.html' %}
{% block content %}
    <h3>Contato</h3>
    <p><b>email:</b> contato@exemplo.com.br</p>
    <p>
        <a href="{% url 'seriados:about' %}">Sobre</a>
    </p>
{% endblock content %}

server/seriados/templates/details.html
{% extends 'base.html' %}
{% block content %}
    <h1>Detalhes de {{ title }}</h1>
    <table border="1px">
        <tr>
            {% for row in data %}<th>{{ row.label }}</th>{% endfor %}
            <th>Edição</th>
            <th>Remoção</th>
        </tr>
        <tr>
            {% for row in data %}<td>{{ row.value }}</td>{% endfor %}
            <td>
                <a href="editar">Editar...</a>
            </td>
            <td>
                <a href="excluir">Excluir...</a>
            </td>
        </tr>
    </table>
{% endblock content %}

server/seriados/templates/form_generic.html
{% extends 'base.html' %}

{% block content %}
<br>
<form action="." method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Enviar">
</form>
{% endblock  %}

server/seriados/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-6 col-md-4">
            <img src="{% static 'seriados/star-icon.png' %}" alt="imagem">
        </div>
        <div class="col-6 col-md-8">
            <h3>Procurar Séries</h3>
            <input id='input_search' type="text" placeholder="Search..">
            <button id="btn_search">Procurar Séries</button>
        </div>
        <img src="{% static 'seriados/dUc2tN.jpg' %}" no-repeat>
    </div>




    <script type="text/javascript">
        $(document).ready(function() {
            $("#btn_search").click(function() {
                search = $("#input_search").val();
                url = '{% url 'seriados:series_list' %}' + '?' +  $.param({search:search});
                window.location.href = url;
            });
        });
        </script> 

{% endblock %}

server/seriados/templates/list.html
{% extends 'base.html' %}
{% block content %}
    <h1>Lista de {{ title }}</h1>
    <td><a href="inserir">Nova {{ title }}...</a></td>
    <br>
    <br>
    <table border="1px">
        <tr>
            {% for label in labels %}<th>{{ label }}</th>{% endfor %}
            <th>Detalhes</th>
            <th>Edição</th>
            <th>Remoção</th>
        </tr>
        {% for row in rows %}
            <tr>
                {% for value in row.data %}
                    <td>{{ value }}</td>
                {% endfor %}
                <td><a href={% url detail_url pk=row.pk %}>Ver...</a></td>
                <td><a href={% url detail_url pk=row.pk%}editar>Editar...</a></td>
                <td><a href={% url detail_url pk=row.pk %}excluir>Excluir...</a></td>

            </tr>
        {% endfor %}
    </table>

    <h3>Procurar {{ title }}</h3>

    <input id='input_search' type="text" placeholder="Search.."/>
    <button id="btn_search">Procurar {{ title }}</button>

    <script type="text/javascript">
        $(document).ready(function() {
            $("#btn_search").click(function() {
                search = $("#input_search").val();
                url = '{% url list_url %}' + '?' +  $.param({search:search});
                window.location.href = url;
            });
        });
    </script>

{% endblock content %}

server/seriados/templates/revisores_cohfirm_delete.html
{% extends 'base.html' %}

{% block  content %}
<br>
Quer deletar o revisor {{object.user}} ?<br /><br />

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>

{% endblock  %}



server/seriados/templates/series_cohfirm_delete.html
{% extends 'base.html' %}

{% block  content %}
<br>
Quer deletar a série {{object.nome}}  ?<br />
<br>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>

{% endblock  %}



server/seriados/templates/series_details.html
{% extends 'base.html' %}
{% block content %}
    <h1>
        Detalhes da Séries</h1>
        <table border="1px">
            <tr>
                <th>Série</th>
                <th>Edição</th>
                <th>Remoção</th>
            </tr>
        
            
            <tr>
                <td>{{ object.nome }}</td>
                <td><a href="editar">Editar...</a></td>
                <td><a href="excluir">Excluir...</a></td>
               </tr>
           
        </table>
        
{% endblock content %}

server/seriados/templates/temporada_cohfirm_delete.html
{% extends 'base.html' %}

{% block content %}
<br>
Quer deletar a temporada {{object.numero}} da Série
{{object.serie.nome}}? <br />
<br>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>

{% endblock  %}



server/seriados/templates/temporada_details.html
{% extends 'base.html' %}
{% block content %}
    <h1>
        Detalhes da Temporada</h1>
        <table border="1px">
            <tr>
                <th>Série</th>
                <th>Temporada</th>
                <th>Edição</th>
                <th>Remoção</th>
            </tr>
        
            
            <tr>
                <td>{{ object.serie.nome }}</td>
                <td>{{ object.numero }}</td>
                <td><a href="editar">Editar...</a></td>
                <td><a href="excluir">Excluir...</a></td>
               </tr>
           
        </table>
        
{% endblock content %}

server/seriados/templates/temporada_list.html
{% extends "base.html" %}

{% block content %}
<h1>Lista de Temporadas</h1>
<td><a href="inserir">Nova Temporadas...</a></td>
<br>
<br>

<table border="1px">
    <tr>
        <th>Série</th>
        <th>Temporada</th>
        <th>Detalhes</th>
        <th>Edição</th>
        <th>Remoção</th>
    </tr>

    {% for object in object_list %}
        <tr>
            <td>{{ object.serie.nome }}</td>
            <td>{{ object.numero }}</td>
            <td><a href="{{ object.get_absolute_url }}">Ver...</a></td>
            <td><a href="{{ object.pk }}/editar">Editar...</a></td>
            <td><a href="{{ object.pk }}/excluir">Excluir...</a></td>
        </tr>
        
    {% endfor %}
    
</table>

<h3>Procurar por temporada</h3>

<input id='input_search' type="text" placeholder="Search.."/>
<button id="btn_search">Procurar por temporada</button>


<script type="text/javascript">
    $(document).ready(function() {
        $("#btn_search").click(function() {
            search = $("#input_search").val();
            url = '{% url 'seriados:temporadas_list' %}' + '?' +  $.param({search:search});
            window.location.href = url;
        });
    });
    </script>

{% endblock %}